# -*- coding: utf-8 -*-
"""NLP02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YkW1hJqclxUee3WMBsTtJrrtHmZ4SQpq
"""

# 問題を解くにあたって必要なファイルを取得
!wget https://nlp100.github.io/data/popular-names.txt

# sample このような形でファイルを扱うことができます
filename="popular-names.txt"
with open(filename) as f:
    for line in f: #1行だけ出力
        print(line,end=" ")
        break

#12番　田嶋
with open('col1.txt', 'w', encoding='utf-8') \
as f1:
    with open('col2.txt', 'w', encoding='utf-8') as f2:
        with open(filename, encoding='utf-8') as f:
            for line in f:
                baby_info = line.strip('\n').split()
                f1.write(baby_info[0] + '\n')
                f2.write(baby_info[1] + '\n')

#12 unix
cut -f 1 filename> col1.txt
cut -f 2 filename> col2.txt

#13番　田嶋
with open('cols.txt', 'w', encoding='utf-8') as f:
    with open('col1.txt', encoding='utf-8') as f1:
        with open('col2.txt', encoding='utf-8') as f2:
            while True:
                r1 = f1.readline()
                r2 = f2.readline()
                f.write(r1.strip('\n') + '\t' + r2)
                if not r1:
                    break

#13 unix
paste col1.txt col2.txt > cols.txt
cat cols.txt

#16 林
N = 2
with open("popular-names.txt", encoding="UTF-8") as f:
    text_list = f.readlines()
    n = int(len(text_list) / N)
    for i in range(0,len(text_list),n):
        file_name = "split" + str(int(i/n)+1) + ".txt"
        with open (file_name,"w",encoding="UTF-8") as f2:
            t = "\n".join(text_list[i*n:(i+1)*n])
            f2.write(t)

#16 UNIX
split -n 2 popular-names.txt

#17 林
with open("popular-names.txt",encoding="UTF-8")as f:
    text_list = f.readlines()
    name_list = []
    for text in text_list:
        name_list.append(text.split("\t")[0])
    name_set = set(name_list)
    print("\n".join(name_set))

#17 UNIX
! cut -f 1 popular-names.txt | sort | uniq

#18 ひがさ
from operator import itemgetter
with open('hightemp.txt') as f:
    descend = []
    for line in f:
        descend.append(line.split('\t'))
    for i in range(len(descend)):
        descend[i][2] = float(descend[i][2])

sorted_list=sorted(descend, key=itemgetter(2),reverse = True)
for i in range(len(sorted_list)):
    sorted_list[i][2] = str(sorted_list[i][2])
    print('\t'.join(sorted_list[i]),end='')

#pandas 岸本
import pandas as pd
data = pd.read_table("popular-names.txt",header=None)
data_sorted = data.sort_values(2,ascending=False)
pd.set_option('display.max_rows', None)
data_sorted

#18 UNIX
! sort -nrk3 hightemp.txt

#19 ひがさ
city = []
with open('hightemp.txt') as f:
    for line in f:
        city.append(line.split('\t')[0])
d = dict()
for i in range(len(city)):
    if city[i] in d:
        d[city[i]] = d[city[i]]+1
    else:
        d[city[i]] = 1
d2 = sorted(d.items(), key = lambda x:x[1],reverse = True)
print(d2)

#pandas 岸本
import pandas as pd
data = pd.read_table("popular-names.txt",header=None)
pd.set_option('display.max_rows', None)
data[0].value_counts()

# 19 UNIX
!  cut -f1 hightemp.txt |sort |uniq -c|sort -rk1