# -*- coding: utf-8 -*-
"""NLP01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18vqhXt7aB0MMAHd496Vd6ZQKzvHsTss6
"""

# 00　ふじもり
str="stressed"
print(str[::-1])

# 01　ふじもり
str="パタトクカシーー"
print(str[0: :2])

# 02　ふじもり
a="パトカー"
b="タクシー"
res=""
for x,y in zip(a,b):
  res+=x
  res+=y

print(res)

# 03 いはら
input_str3="Now I need a drink, alcoholic of course, after the heavy lectures involving quantum mechanics."
output_list3=list()

word_list3=input_str3.split( )

for item in word_list3:
    item=item.rstrip(",")
    item=item.rstrip(".")
    output_list3.append(len(item))

print(output_list3)

# 04 いはら
def strip(word):
    word=word.rstrip(",")
    word=word.rstrip(".")
    return(word)

output_dic4=dict()
input_str4="Hi He Lied Because Boron Could Not Oxidize Fluorine. New Nations Might Also Sign Peace Security Clause. Arthur King Can."
 
word_list4=input_str4.split( )
word_list4=list(map(strip,word_list4))

for i in range(0,len(word_list4)):
    if (i+1) in [1,5,6,7,8,9,15,16,19]:
        output_dic4[word_list4[i][0]]=i+1
    else:
        output_dic4[word_list4[i][0]+word_list4[i][1]]=i+1
        
print(output_dic4)

# 05 きしもと
def n_gram(seq,n):
    return[seq[i:i+n] for i in range(len(seq)-n+1)]

seq = "I am an NLPer"
print("文字bi-gram")
print(n_gram(seq,2))

seq = seq.split()
print("単語bi-gram")
print(n_gram(seq,2))

# 0６ きしもと
def n_gram(seq,n):
    return[seq[i:i+n] for i in range(len(seq)-n+1)]

seq1 = "paraparaparadise"
seq2 = "paragraph"
X = set(n_gram(seq1,2))
Y = set(n_gram(seq2,2))

print("和集合")
print(X|Y)
print("積集合")
print(X&Y)
print("差集合")
print(X-Y)
print(Y-X)

print("'se'はXに含まれるか？含まれるならTrueを返す")
print("se" in X)
print("'se'はYに含まれるか？含まれるならTrueを返す")
print("se" in Y)

# 08 しもかわ
def n_gram(seq,n):
    return[seq[i:i+n] for i in range(len(seq)-n+1)]
def cipher(string):
    string_list = n_gram(string, 1)
    for i in range(len(string_list)):
        if string_list[i].islower():
            string_list[i] = chr(219 - ord(string_list[i]))
    return ''.join(string_list)

string = "Now I need a drink, alcoholic of course, after the heavy lectures involving quantum mechanics."
print(cipher(string))
print(cipher(cipher(string)))

# 09 しもかわ
import random
def shuffle(string):
    string_list = string.split(" ")
    for i in range(len(string_list)):
        if len(string_list[i]) > 4:
            head = string_list[i][0]
            other = string_list[i][1:]
            other = ''.join(random.sample(other, len(other)))
            string_list[i] = head+other
    return ' '.join(string_list)
string = "I couldn’t believe that I could actually understand what I was reading : the phenomenal power of the human mind ."
print(shuffle(string))

